# Provider hints
providers = ["python"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PIP_NO_CACHE_DIR = "true"

[phases.setup]
nixPkgs = ["python311Full"]
aptPkgs = ["python3-pip"]

[phases.install]
dependsOn = ["setup"]
cmds = ["cd backend && pip3 install -r requirements.txt"]

[start]
cmd = "cd backend && gunicorn app:app --bind 0.0.0.0:$PORT"
